name       : cgns
version    : 4.2.0
release    : 4
source     :
    - https://github.com/CGNS/CGNS/archive/refs/tags/v4.2.0.tar.gz : 090ec6cb0916d90c16790183fc7c2bd2bd7e9a5e3764b36c8196ba37bf1dc817
license    : Zlib
component  : programming.library
homepage   : https://cgns.github.io/
summary    : CFD General Notation System
description: |
    The CFD General Notation System (CGNS) provides a standard for recording and recovering computer data associated with the numerical solution of fluid dynamics equations.
builddeps  :
    - pkgconfig(hdf5)
setup      : |
    %cmake_ninja \
        -DCGNS_BUILD_SHARED=ON \
        -DCGNS_ENABLE_HDF5=ON \
        -DCMAKE_PREFIX_PATH=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
