name       : cgns
version    : 4.1.2
release    : 1
source     :
    - https://github.com/CGNS/CGNS/archive/v4.1.2.tar.gz : 951653956f509b8a64040f1440c77f5ee0e6e2bf0a9eef1248d370f60a400050
license    : Zlib
component  : programming.library
homepage   : https://cgns.github.io/
summary    : CFD General Notation System
description: |
    The CFD General Notation System (CGNS) provides a standard for recording and recovering computer data associated with the numerical solution of fluid dynamics equations.
builddeps  :
    - pkgconfig(hdf5)
setup      : |
    %cmake_ninja \
        -DCGNS_BUILD_SHARED=ON \
        -DCGNS_ENABLE_HDF5=ON \
        -DCMAKE_PREFIX_PATH=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
